const ShopActionTypes = {
    FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SCCESS:'FETCH_COLLECTIONS_SCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_FAILURE'

  };
  
  export default ShopActionTypes;